### ISSUE TITLE
rouge not loaded

### ISSUE THREAD

**Issue by pddzaic** [rouge-ruby/rouge#1455] opened 2020-03-07 12:19 UTC
Since today I have the following error message when trying to use the rouge-gem. 

```

C:\Users\ped>gem list rouge

*** LOCAL GEMS ***

rouge (3.16.0)

C:\Users\ped>irb
irb(main):001:0> require "rouge"                                                                                                     Traceback (most recent call last):
       12: from C:/PortableApps/Ruby/ruby26/bin/irb:23:in `<main>'
       11: from C:/PortableApps/Ruby/ruby26/bin/irb:23:in `load'
       10: from C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        9: from (irb):1
        8: from C:/PortableApps/Ruby/Ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        7: from C:/PortableApps/Ruby/Ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        6: from C:/PortableApps/Ruby/Ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
        5: from C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge.rb:55:in `<top (required)>'
        4: from C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge.rb:55:in `each'
        3: from C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge.rb:55:in `block in <top (required)>'
        2: from C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge/lexer.rb:513:in `load_lexer'
        1: from C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge/lexer.rb:513:in `load'
LoadError (cannot load such file -- C:/PortableApps/Ruby/Ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge/lexers/C:/PortableApps/Ruby/ruby26/lib/ruby/gems/2.6.0/gems/rouge-3.16.0/lib/rouge/lexers/abap.rb)
irb(main):002:0>  
```

Its seems, that the value of the variable "relpath" is the absolute path:

```
  module Lexers
    @_loaded_lexers = {}

    def self.load_lexer(relpath)
      return if @_loaded_lexers.key?(relpath)
      @_loaded_lexers[relpath] = true
      load File.join(__dir__, 'lexers', relpath)
    end
  end
```

I could track the error to line 55 in rouge.rb (puts added by by me):

```
Dir.glob(lexer_dir('*rb')).each { |f|
puts "lexer_dir: #{lexer_dir}" 
puts "f: #{f}"
puts "f.sub(lexer_dir, ''): #{f.sub(lexer_dir, '')}"  # <-- Does not work

Rouge::Lexers.load_lexer(f.sub(lexer_dir, '')) }
```

Changing to `Dir.glob(lexer_dir('*rb')).each { |f| Rouge::Lexers.load_lexer(f.sub(lexer_dir, '')) }` to 
`Dir.glob(lexer_dir('*rb')).each { |f| Rouge::Lexers.load_lexer(File.basename(f)) }` solves the problem.

**Comment by ashmaroli** [comment] 2020-03-07 16:13
Why do you have two different Ruby directories:
- `C:/PortableApps/Ruby/Ruby26/`
- `C:/PortableApps/Ruby/ruby26/`

**Comment by pyrmont** [comment] 2020-03-08 07:50
@pddzaic I haven't looked into the code closely but it looks like the issue is being caused by Rouge not distinguishing between uppercase and lowercase letters in your directory names. Ash's question got at this but do you have two directories, `C:\PortableApps\Ruby\Ruby26\` and `C:\PortableApps\Ruby\Ruby26\`?

**Comment by pddzaic** [comment] 2020-03-08 09:11
Now I understood the problem. I'am using Windows and have added Ruby to the PATH-variable as `C:\PortableApps\Ruby\Ruby26\`, but the real folder name is `C:\PortableApps\Ruby\ruby26\` .

Windows is not case-sensitive, but string comparison in Ruby is. :-)

I am not sure if this behavior in rouge can be considered a bug. If not, please delete my post.

Thank you very much for your help!

**Comment by ashmaroli** [comment] 2020-03-08 09:35
@pddzaic Technically, it is a bug. But one that cannot be fixed easily. (Not impossible, just not simple and straight-forward either). If this whole issue can be resolved by *correcting* the PATH variable at your end, then I believe that would be a win-win situation for both parties.

*After your make the correction at your end, you can run `gem env` to get insight on all paths that may have an effect on Ruby..*

**Comment by pyrmont** [comment] 2020-03-08 10:11
@pddzaic Yeah, I think while this is probably technically a bug, since it doesn't seem to have had much of an impact broadly I'll close it for now. We'll reevaluate our response if we see more people experiencing a similar issue.

Thanks @ashmaroli for your help!

**Closed by pyrmont** 2020-03-08 10:11 UTC
Labels: bugfix-request
