### ISSUE TITLE
C# last-line comment not parsed correctly

### ISSUE THREAD

**Issue by wangchj** [rouge-ruby/rouge#466] opened 2016-05-16 06:23 UTC
If a line of comment is the last line in the source code, then it is not parsed properly as a comment. Consider the following example

``` C#
//Write SQL statement
string queryStr = "SELECT eventId, eventName, startTime FROM [Events] " +
    "WHERE creatorId=@cid AND approved=1 AND endTime>@now " +
    "ORDER BY [Events].startTime";

//Create connection and query parameters
SqlConnection con = new SqlConnection(Config.SqlConStr);
SqlCommand command = new SqlCommand(queryStr, con);
command.Parameters.Add(new SqlParameter("cid", userId));
command.Parameters.Add(new SqlParameter("now", DateTime.Now));
con.Open();

//Execute query
SqlDataReader reader = command.ExecuteReader();

//Create HTML table and for each record, create table row, etc..
```

**Comment by jneen** [comment] 2016-06-01 21:39
Ah yep. That's because it's scanning for `\n` again in the comment regex.

**Comment by BigChief45** [comment] 2017-06-06 02:17
Was this fixed? I cannot seem to reproduce this. 

I am using rougify to highlight the code. The last comment line is being highlighted as a comment just fine...

**Comment by miparnisari** [comment] 2019-06-13 03:24
This works fine for me, but I don't understand @jneen's comment. The comment regexes look OK...

```ruby
        rule %r(//.*?$), Comment::Single
        rule %r(/[*].*?[*]/)m, Comment::Multiline
```

![image](https://user-images.githubusercontent.com/5374887/59401539-e4ad3480-8d4f-11e9-9888-5f68d411ab5e.png)

**Comment by pyrmont** [comment] 2019-06-13 03:27
@miparnisari So @jneen's saying that the comment regex (at the time anyway) needed to end in a newline to match. However, if a comment is the last line of a file, there is no new line and so it doesn't match.

This is no longer how the regex works:

https://github.com/rouge-ruby/rouge/blob/ea99dc41e1ceb3d0bb281318560af8ff516296e0/lib/rouge/lexers/csharp.rb#L47

And so you're not seeing the problem anymore. I'll close this, thanks!

**Closed by pyrmont** 2019-06-13 03:27 UTC
Labels: bugfix-request, low-complexity

**Comment by miparnisari** [comment] 2019-06-13 03:30
Ah! It was fixed in this commit: https://github.com/rouge-ruby/rouge/commit/d022e7ef26c9470ac4d8e2932038eb6bd4ebe314
