### ISSUE TITLE
gem homepage metadata is broken

### ISSUE THREAD

**Issue by zenspider** [rouge-ruby/rouge#1959] opened 2023-05-07 22:17 UTC
goes to http://rouge.jneen.net which prolly died when heroku went corrupt

**Comment by jneen** [comment] 2023-05-07 22:49
Yep, I still need to put it up on my server. Unless maybe gitlab wants to host it?

**Comment by tancnle** [comment] 2023-06-06 00:24
Closing as duplicate of https://github.com/rouge-ruby/rouge/issues/1902

**Comment by tancnle** [comment] 2023-06-06 00:24
> Unless maybe gitlab wants to host it?

I will check with the folks at GitLab and get back to you on this.

**Closed by tancnle** 2023-06-06 00:24 UTC
