### ISSUE TITLE
Rouge lexer request for agda

### ISSUE THREAD

**Issue by pnlph** [rouge-ruby/rouge#1226] opened 2019-06-26 07:25 UTC
Hi, i see that you already support haskell in rouge.

Maybe it would be not so difficult to support also Agda, a dependently typed functional programming language and proof assistant.

There is already a [pigments class](http://pygments.org/docs/lexers/) `pygments.lexers.haskell.AgdaLexer`

**Comment by pyrmont** [comment] 2019-06-26 07:38
Thanks for the interest in Rouge, @pnlph :)

There's an existing request for Agda support (PR #709) but I'm afraid this is the kind of thing where we're largely dependent on the community. If you'd like to try your hand at making a lexer for Agda, have a look at [the lexer development guide](https://www.rubydoc.info/github/rouge-ruby/rouge/master/file/docs/LexerDevelopment.md).

I'll close this issue as a duplicate of #709; please feel free to continue the discussion there.

**Closed by pyrmont** 2019-06-26 07:38 UTC
Labels: lexer-request
